# This file should not be modified as it may get changed by the maintainer.
# Add extra configuration files in the extra_config_files directory to override
# the content from this file

# Extra configuration directory where the config files overriding this file
# should be.
extra_config_files: /etc/wazo-confd/conf.d/

# Change the log level to debug level.
debug: false

# Change the log level. Values are: critical, error, warning, info, debug.
log_level: info

# Log file.
log_filename: /var/log/wazo-confd.log

# PID file.
pid_filename: /var/run/wazo-confd/wazo-confd.pid

db_uri: postgresql://asterisk:proformatique@postgres/asterisk

service_discovery:
  enabled: false

# REST API server
rest_api:

  enabled: true
  listen: 0.0.0.0
  port: 9486

  certificate: /usr/share/xivo-certs/server.crt
  private_key: /usr/share/xivo-certs/server.key

  cors:
    #CORS configuration. See Flask-CORS documentation for other values.

    #Enabled by default
    enabled: true

    #Allow JSON preflight requests
    allow_headers: [Content-Type, X-Auth-Token]

# Event bus (AMQP) connection informations
bus:
    username: guest
    password: guest
    host: rabbitmq
    port: 5672
    exchange_name: xivo
    exchange_type: topic
    exchange_durable: True

# wazo-provd connection informations.
provd:
    host: provd
    port: 8666

# xivo-sysconfd connection informations.
sysconfd:
    host: sysconfd
    port: 8668

ari:
    host: ari
    port: 5039

auth:
    host: auth
    port: 9497
    verify_certificate: False

uuid: 25a8940f-b563-4537-81d0-ccd40c841a2c
