# This file should not be modified as it may get changed by the maintainer.
# Add extra configuration files to the extra_config_files directory to override
# the settings in this file

# Directory in which to place config overrides
extra_config_files: /etc/wazo-confd/conf.d/

# Change the log level to debug level.
debug: false

# Change the log level. Values are: critical, error, warning, info, debug.
log_level: info

# Log file.
log_filename: /var/log/wazo-confd.log

# REST API server
rest_api:

  listen: 127.0.0.1
  port: 9486

  cors:
    # CORS configuration. See Flask-CORS documentation for other values.

    # Enabled by default
    enabled: true

    # Allow JSON preflight requests
    allow_headers: [Content-Type, X-Auth-Token, Wazo-Tenant]


# wazo-auth connection settings
auth:
    host: localhost
    port: 9497
    prefix: null
    https: false

# Asterisk ARI connection settings
ari:
  host: localhost
  port: 5039
  username: xivo
  password: Nasheow8Eag

# Event bus (AMQP) connection settings
bus:
    username: guest
    password: guest
    host: localhost
    port: 5672
    exchange_name: xivo
    exchange_type: topic
    exchange_durable: True
    subscribe_exchange_name: wazo-headers

# wazo-provd connection settings
provd:
    host: localhost
    port: 8666
    prefix: null
    https: false

# wazo-sysconfd connection settings
sysconfd:
    host: localhost
    port: 8668

service_discovery:
  enabled: false

# Example of service discovery settings
#
# Necessary to use service discovery
# consul:
#   scheme: http
#   host: localhost
#   port: 8500
#   token: 'the_one_ring'
#
# # All time intervals are in seconds
# service_discovery:
#   # Indicates whether of not to use service discovery.
#   enabled: true
#   # The address that will be received by other services using service discovery.
#   # Use "advertise_address: auto" to enable ip address detection based on
#   # advertise_address_interface
#   advertise_address: auto
#   # If advertise_address is "auto" this interface will be used to find the ip
#   # address to advertise. Ignored otherwise
#   advertise_address_interface: eth0
#   advertise_port: 9486
#   # The number of seconds that consul will wait between 2 ttl messages to mark
#   # this service as up
#   ttl_interval: 30
#   # The time interval before the service sends a new ttl message to consul
#   refresh_interval: 27
#   # The time interval to detect that the service is running when starting
#   retry_interval: 2
#   extra_tags: []

# Activate confd plugins
# This is the recommended way to add plugins.
# enabled_plugins:
#     user: true
