# This file should not be modified as it may get changed by the maintainer.
# Add extra configuration files in the extra_config_files directory to override
# the content from this file

# Extra configuration directory where the config files overriding this file
# should be.
extra_config_files: /etc/xivo-confd/conf.d/

# Change the log level to debug level.
debug: false

# Change the log level. Values are: critical, error, warning, info, debug.
log_level: info

# Log file.
log_filename: /var/log/xivo-confd.log

# PID file.
pid_filename: /var/run/xivo-confd/xivo-confd.pid

db_uri: postgresql://asterisk:proformatique@postgres/asterisk

# REST API server
rest_api:

    # Listening address
    listen: 0.0.0.0

    # Listening port
    port: 9486

    #CORS configuration. See Flask-CORS documentation for other values.
    cors:

        #Enabled by default
        enabled: true

        #Allow JSON preflight requests
        allow_headers: Content-Type


# Event bus (AMQP) connection informations
bus:
    username: guest
    password: guest
    host: rabbitmq
    port: 5672
    exchange_name: xivo
    exchange_type: topic
    exchange_durable: True

# xivo-provd connection informations.
provd:
    host: provd
    port: 8666

# xivo-sysconfd connection informations.
sysconfd:
    host: sysconfd
    port: 8668

# Extra resources to load.
# This is deprecated and for retro-compatibility only.
#extra_plugins:
#   - resource_name


# Activate confd plugins
# This is the recommended way to add plugins.
enabled_plugins:
   - legacy_plugins
   - line_plugin
   - endpoint_sip_plugin
   - endpoint_sccp_plugin
   - line_sip_plugin
   - user_line_plugin
   - line_extension_plugin
   - line_endpoint_plugin
