provd:
  image: xivo/xivo-provd
  ports:
    - "8666:8666"
  expose:
    - "8666"
  volumes:
    - "./etc/xivo-provd/provd.conf:/etc/xivo/provd/provd.conf"
postgres:
  image: xivo/xivo-postgres
  expose:
    - "5432"
  ports:
    - "15432:5432"
  volumes:
    - "./etc/xivo-postgres/populate.sql:/docker-entrypoint-initdb.d/populate.sql"
    - "./etc/xivo-postgres/fsync_off.sh:/docker-entrypoint-initdb.d/fsync_off.sh"
rabbitmq:
  image: rabbitmq
  expose:
    - "5672"
sysconfd:
  image: nickstenning/flask
  expose:
    - "8668"
  ports:
    - "18668:8668"
  volumes:
    - "./mocks/sysconfd.py:/tmp/sysconfd.py"
  command: "python /tmp/sysconfd.py"
confd:
  image: xivo-confd-test
  expose:
    - "9486"
  ports:
    - "9486:9486"
  links:
    - postgres
    - rabbitmq
    - provd
    - sysconfd
  command: "xivo-confd -f -d"
  volumes:
    - "../../..:/usr/src/xivo-confd"
    - "./etc/xivo-confd:/etc/xivo-confd"
    - "/home/gregory/p/xivo-dao/xivo_dao:/usr/local/lib/python2.7/site-packages/xivo_dao"
testdeps:
  # This image checks that all the links are up by pinging the ports.
  # Used to make sure everything is ready before executing tests
  image: n3llyb0y/wait
  links:
    - rabbitmq
    - postgres
    - provd
    - sysconfd
  environment:
    PORTS: "5672 5432 8666 8668"
    TIMEOUT: "60"
tests:
  image: n3llyb0y/wait
  links:
    - rabbitmq
    - postgres
    - provd
    - sysconfd
    - confd
  environment:
    PORTS: "5672 5432 8666 8668 9486"
