version: '3'
services:
  sync:
    depends_on:
      - swagger-validator
    environment:
      TARGETS: "swagger-validator:8080,postgres:5432,confd:9486"

  swagger-validator:
    image: swaggerapi/swagger-validator
    ports:
      - "8080"
    links:
      - confd
