version: '3.7'
services:
  sync:
    image: wazopbx/wait
    environment:
      TIMEOUT: ${INTEGRATION_TEST_TIMEOUT}

  auth:
    image: wazopbx/wazo-auth-mock
    ports:
      - 9497

  provd:
    image: wazopbx/wazo-provd
    ports:
      - "8666"
    volumes:
      - "./etc/wazo-provd/config.yml:/etc/wazo-provd/config.yml"
      - "./keys/wazo-provd-key.yml:/var/lib/wazo-auth-keys/wazo-provd-key.yml"
      - "./provd/null:/var/lib/wazo-provd/plugins/null"
      - "./provd/zero:/var/lib/wazo-provd/plugins/zero"

  postgres:
    image: wazopbx/postgres-test
    ports:
      - "5432"

  rabbitmq:
    image: rabbitmq
    ports:
      - "5672"
    volumes:
      - type: tmpfs
        target: /var/lib/rabbitmq

  sysconfd:
    image: p0bailey/docker-flask
    ports:
      - "8668"
    volumes:
      - "./mocks/sysconfd.py:/tmp/sysconfd.py"
    command: "python /tmp/sysconfd.py"

  confd:
    image: wazo-confd-test
    ports:
      - "9486"
    command: "wazo-confd -d"
    volumes:
      - "../..:/usr/src/wazo-confd"
      - "./etc/wazo-confd/conf.d/50-default.yml:/etc/wazo-confd/conf.d/50-default.yml"
      - "./keys/wazo-confd-key.yml:/var/lib/wazo-auth-keys/wazo-confd-key.yml"
      - "./doc/pjsip.json.gz:/usr/share/doc/asterisk-doc/json/pjsip.json.gz"

      - "./etc/ssl:/usr/share/xivo-certs"
      # - "${LOCAL_GIT_REPOS}/wazo-auth-client/wazo_auth_client:/usr/local/lib/python3.7/site-packages/wazo_auth_client"
      # - "${LOCAL_GIT_REPOS}/wazo-provd-client/wazo_provd_client:/usr/local/lib/python3.7/site-packages/wazo_provd_client"
      # - "${LOCAL_GIT_REPOS}/xivo-bus/xivo_bus:/usr/local/lib/python3.7/site-packages/xivo_bus"
      # - "${LOCAL_GIT_REPOS}/xivo-dao/xivo_dao:/usr/local/lib/python3.7/site-packages/xivo_dao"
      # - "${LOCAL_GIT_REPOS}/xivo-lib-python/xivo:/usr/local/lib/python3.7/site-packages/xivo"
