version: '3.7'
services:
  sync:
    depends_on:
      - postgres
      - confd
      - swagger-validator
    environment:
      TARGETS: "swagger-validator:8080,postgres:5432,confd:9486"

  swagger-validator:
    image: swaggerapi/swagger-validator
    ports:
      - "8080"
    links:
      - confd
