version: '3.7'
services:
  sync:
    image: wazopbx/wait
    environment:
      TIMEOUT: ${INTEGRATION_TEST_TIMEOUT}

  auth:
    image: wazopbx/xivo-auth-mock
    ports:
      - 9497
    volumes:
      - ./ssl:/usr/local/share/ssl

  provd:
    image: wazopbx/xivo-provd
    ports:
      - "8666"
    volumes:
      - "./etc/xivo-provd/provd.conf:/etc/xivo/provd/provd.conf"
      - "./provd/null:/var/lib/xivo-provd/plugins/null"
      - "./provd/zero:/var/lib/xivo-provd/plugins/zero"

  postgres:
    image: wazopbx/postgres-test
    ports:
      - "5432"

  rabbitmq:
    image: rabbitmq
    ports:
      - "5672"
    volumes:
      - type: tmpfs
        target: /var/lib/rabbitmq

  sysconfd:
    image: p0bailey/docker-flask
    ports:
      - "8668"
    volumes:
      - "./mocks/sysconfd.py:/tmp/sysconfd.py"
    command: "python /tmp/sysconfd.py"

  confd:
    image: xivo-confd-test
    ports:
      - "9486"
    command: "xivo-confd -d"
    volumes:
      - "../..:/usr/src/xivo-confd"
      - "./etc/xivo-confd/conf.d/uuid.yml:/etc/xivo-confd/conf.d/uuid.yml"
      - "./etc/xivo-confd/conf.d/debug.yml:/etc/xivo-confd/conf.d/debug.yml"
      - "./etc/xivo-confd/conf.d/postgres.yml:/etc/xivo-confd/conf.d/postgres.yml"
      - "./etc/xivo-confd/conf.d/auth.yml:/etc/xivo-confd/conf.d/auth.yml"
      - "./etc/xivo-confd/conf.d/rabbitmq.yml:/etc/xivo-confd/conf.d/rabbitmq.yml"
      - "./etc/xivo-confd/conf.d/provd.yml:/etc/xivo-confd/conf.d/provd.yml"
      - "./etc/xivo-confd/conf.d/sysconfd.yml:/etc/xivo-confd/conf.d/sysconfd.yml"
      - "./etc/xivo-confd/conf.d/disable_service_discovery.yml:/etc/xivo-confd/conf.d/disable_service_discovery.yml"
      - "./keys/xivo-confd-key.yml:/var/lib/wazo-auth-keys/xivo-confd-key.yml"

      - "./etc/ssl:/usr/share/xivo-certs"
      # - "${LOCAL_GIT_REPOS}/xivo-lib-python/xivo:/usr/local/lib/python2.7/site-packages/xivo"
      # - "${LOCAL_GIT_REPOS}/xivo-dao/xivo_dao:/usr/local/lib/python2.7/site-packages/xivo_dao"
      # - "${LOCAL_GIT_REPOS}/xivo-bus/xivo_bus:/usr/local/lib/python2.7/site-packages/xivo_bus"
      # - "${LOCAL_GIT_REPOS}/xivo-auth-client/xivo_auth_client:/usr/local/lib/python2.7/site-packages/xivo_auth_client"
