version: '3'
services:
  sync:
    image: waisbrot/wait
    depends_on:
      - auth
      - postgres
      - provd
      - rabbitmq
      - sysconfd
      - dird
      - confd
    environment:
      TARGETS: "postgres:5432,rabbitmq:5672,provd:8666,sysconfd:8668,auth:9497,dird:9489,confd:9486"
      TIMEOUT: ${INTEGRATION_TEST_TIMEOUT}

  provd:
    image: wazopbx/xivo-provd
    ports:
      - "8666"
    volumes:
      - "./etc/xivo-provd/provd.conf:/etc/xivo/provd/provd.conf"

  postgres:
    image: wazopbx/postgres
    ports:
      - "5432"

  rabbitmq:
    image: rabbitmq
    ports:
      - "5672"

  sysconfd:
    image: p0bailey/docker-flask
    ports:
      - "8668"
    volumes:
      - "./mocks/sysconfd.py:/tmp/sysconfd.py"
    command: "python /tmp/sysconfd.py"

  auth:
    image: p0bailey/docker-flask
    expose:
      - "9497"
    volumes:
      - "./mocks/auth.py:/tmp/auth.py"
    command: "python /tmp/auth.py"

  dird:
    image: p0bailey/docker-flask
    expose:
      - "9489"
    volumes:
      - "./mocks/dird.py:/tmp/dird.py"
    command: "python /tmp/dird.py"

  confd:
    image: xivo-confd-test
    ports:
      - "9486"
    command: "xivo-confd -d"
    volumes:
      - "../../..:/usr/src/xivo-confd"
      - "./etc/xivo-confd:/etc/xivo-confd"
      - "./etc/ssl:/usr/share/xivo-certs"
      - "./etc/timezone:/etc/timezone"
      - "./var/lib/xivo-auth-keys/xivo-wizard-key.yml:/var/lib/xivo-auth-keys/xivo-wizard-key.yml"
    domainname: example.com
