provd:
  image: xivo/xivo-provd
  ports:
    - "8666:8666"
  expose:
    - "8666"
  volumes:
    - "./etc/xivo-provd/provd.conf:/etc/xivo/provd/provd.conf"
postgres:
  image: xivo/postgres
  expose:
    - "5432"
  ports:
    - "15432:5432"
rabbitmq:
  image: rabbitmq
  ports:
    - "5672:5672"
sysconfd:
  image: p0bailey/docker-flask
  expose:
    - "8668"
  ports:
    - "18668:8668"
  volumes:
    - "./mocks/sysconfd.py:/tmp/sysconfd.py"
  command: "python /tmp/sysconfd.py"
confd:
  image: xivo-confd-test
  expose:
    - "9486"
  ports:
    - "9486:9486"
  links:
    - postgres
    - rabbitmq
    - provd
    - sysconfd
  command: "xivo-confd -f -d"
  volumes:
    - "../../..:/usr/src/xivo-confd"
    - "./etc/xivo-confd:/etc/xivo-confd"
    - "./etc/ssl:/usr/share/xivo-certs"
    - "./etc/timezone:/etc/timezone"
    - "./etc/resolv.conf:/etc/resolv.conf"
  domainname: example.com
sync:
  image: n3llyb0y/wait
  links:
    - rabbitmq
    - postgres
    - provd
    - sysconfd
    - confd
  environment:
    PORTS: "5432 5672 8666 8668 9486"
    TIMEOUT: "5"
