# Change the log level to debug level.
debug: false

# Change the log level. Values are: critical, error, warning, info, debug.
log_level: info

# Log file.
log_filename: /var/log/xivo-confd.log

# PID file.
pid_filename: /var/run/xivo-confd/xivo-confd.pid

# REST API server
rest_api:

    # Listening address
    listen: 127.0.0.1

    # Listening port
    port: 9487

# Event bus (AMQP) connection informations
bus:
    username: guest
    password: guest
    host: localhost
    port: 5672
    exchange_name: xivo
    exchange_type: topic
    exchange_durable: True
